name: Deploy in ec2

on:
  push:
    branches:
      - without_nft_v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker Image
        run: docker build -t rokondoc/wealth-free-doc .
      - name: Publish image to docker hub
        run: docker push rokondoc/wealth-free-doc:latest

  deploy:
    needs: build
    runs-on: self-hosted
    services:
      docker:
        image: docker:latest
        ports:
          - 2375:2375
    steps:
      - name: Check Docker Info
        run: docker info
      - name: Pull image from docker hub
        run: docker pull rokondoc/wealth-free-doc:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer || true 
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer rokondoc/wealth-free-doc
